### ISSUE TITLE
Upgrade symfony/yaml

### ISSUE THREAD

**Issue by alexweb** [PHLAK/Config#23]
Hello,
could you please upgrade `symfony/yaml` in your library?
from:
`"symfony/yaml": "^3.0 || ^4.0 || ^5.0",`
to:
`"symfony/yaml": "^3.0 || ^4.0 || ^5.0 || ^6.0",`
Because now it doesn't allow us to use latest `symfony/yaml v6.0` and  `php 8.2`
Thanks!

**Comment by Externaluse** [comment]
Check Release 8. It's been upgraded to "symfony/yaml": "^5.0 || ^6.0"
